version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "el10-kitten"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "el10"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns: ["*"]
