[main]
keepcache=1
retries=20
gpgcheck=1
install_weak_deps=0
metadata_expire=-1
best=True
tsflags=nodocs
max_parallel_downloads=20
#reposdir=/dev/null

[terra]
name=Terra EL Kitten $releasever
baseurl=https://repos.fyralabs.com/terrael$releasever-kitten
metadata_expire=0
type=rpm
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-terrael$releasever-kitten
repo_gpgcheck=1
enabled=1
enabled_metadata=1
priority=150
